name: Apply Terraform Code

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "terraform"
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2    
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.26
    
    - name: Check Terraform Formatting
      id: fmt
      run: terraform fmt -check
    
    - name: Check Terraform Init
      id: init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Validate Terraform Code
      id: validate
      run: terraform validate
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    
    - name: Run Terraform Apply
      id: apply
      run: terraform apply --auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        TF_VAR_vault_address: ${{ secrets.VAULT_ADDR }}
        TF_VAR_project: ${{ secrets.GCP_PROJECT_ID }}